language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
install:
  - composer install
script:
  - ./bin/phpunit -c app/
  - ./bin/phpcs --standard=PSR2 src/
  - ./bin/phpcpd src/
  - ./bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode