parameters:
#    levi9_sonata.example.class: Levi9\SonataBundle\Example

services:
#    levi9_sonata.example:
#        class: %levi9_sonata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
